/**
 * AgentVault contract client.
 * Adapted from contracts/packages/vault_sdk/src/index.ts.
 * Only change: @stellar/stellar-sdk → stellar-sdk (same library, different npm scope).
 *
 * Methods (deposit, withdraw, get_balance, …) are auto-generated by ContractClient
 * from the ContractSpec. TypeScript types come from the interface declaration below.
 */
import { Buffer } from 'buffer';
import {
  AssembledTransaction,
  Client as ContractClient,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
  Spec as ContractSpec,
} from 'stellar-sdk/contract';
import type { i128 } from 'stellar-sdk/contract';

if (typeof window !== 'undefined') {
  // @ts-ignore
  window.Buffer = window.Buffer || Buffer;
}

export const VAULT_CONTRACT_ID = 'CCNK5O3FFCOC5KEBRK6ORUUPPHYDUITTH2XCLLG7P2IBQRX2L6HXJFWG';

export const Errors = {
  1: { message: 'NotInitialized' },
  2: { message: 'AlreadyInitialized' },
  3: { message: 'UnsupportedToken' },
  4: { message: 'InsufficientBalance' },
  5: { message: 'Unauthorized' },
};

// Interface provides TypeScript types; runtime methods come from ContractClient
// via declaration merging.
export interface VaultClient {
  deposit(
    args: { user: string; token: string; amount: i128 },
    options?: MethodOptions,
  ): Promise<AssembledTransaction<Result<void>>>;

  withdraw(
    args: { user: string; token: string; amount: i128 },
    options?: MethodOptions,
  ): Promise<AssembledTransaction<Result<void>>>;

  get_balance(
    args: { user: string; token: string },
    options?: MethodOptions,
  ): Promise<AssembledTransaction<i128>>;

  get_terminal_pool(
    args: { token: string },
    options?: MethodOptions,
  ): Promise<AssembledTransaction<i128>>;
}

export class VaultClient extends ContractClient {
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([
        'AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAABQAAAAAAAAAOTm90SW5pdGlhbGl6ZWQAAAAAAAEAAAAAAAAAEkFscmVhZHlJbml0aWFsaXplZAAAAAAAAgAAAAAAAAAQVW5zdXBwb3J0ZWRUb2tlbgAAAAMAAAAAAAAAE0luc3VmZmljaWVudEJhbGFuY2UAAAAABAAAAAAAAAAMVW5hdXRob3JpemVkAAAABQ==',
        'AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAABAAAAAAAAAAAAAAABUFkbWluAAAAAAAAAQAAAAAAAAAOU3VwcG9ydGVkVG9rZW4AAAAAAAEAAAATAAAAAQAAAAAAAAAHQmFsYW5jZQAAAAACAAAAEwAAABMAAAABAAAAAAAAAAxUZXJtaW5hbFBvb2wAAAABAAAAEw==',
        'AAAAAAAAAAAAAAAHZGVwb3NpdAAAAAADAAAAAAAAAAR1c2VyAAAAEwAAAAAAAAAFdG9rZW4AAAAAAAATAAAAAAAAAAZhbW91bnQAAAAAAAsAAAABAAAD6QAAAAIAAAAD',
        'AAAAAAAAAAAAAAAId2l0aGRyYXcAAAADAAAAAAAAAAR1c2VyAAAAEwAAAAAAAAAFdG9rZW4AAAAAAAATAAAAAAAAAAZhbW91bnQAAAAAAAsAAAABAAAD6QAAAAIAAAAD',
        'AAAAAAAAAAAAAAAKaW5pdGlhbGl6ZQAAAAAAAQAAAAAAAAAFYWRtaW4AAAAAAAATAAAAAQAAA+kAAAACAAAAAw==',
        'AAAAAAAAAAAAAAAKc2V0dGxlX3BubAAAAAAAAwAAAAAAAAAEdXNlcgAAABMAAAAAAAAABXRva2VuAAAAAAAAEwAAAAAAAAADcG5sAAAAAAsAAAABAAAD6QAAAAIAAAAD',
        'AAAAAAAAAAAAAAALZ2V0X2JhbGFuY2UAAAAAAgAAAAAAAAAEdXNlcgAAABMAAAAAAAAABXRva2VuAAAAAAAAEwAAAAEAAAAL',
        'AAAAAAAAAAAAAAARZ2V0X3Rlcm1pbmFsX3Bvb2wAAAAAAAABAAAAAAAAAAV0b2tlbgAAAAAAABMAAAABAAAACw==',
        'AAAAAAAAADZBZG1pbiBzZWVkcyB0aGUgcG9vbCB0aGF0IGJhY2tzIHdpbm5pbmctdHJhZGUgcGF5b3V0cy4AAAAAABJmdW5kX3Rlcm1pbmFsX3Bvb2wAAAAAAAIAAAAAAAAABXRva2VuAAAAAAAAEwAAAAAAAAAGYW1vdW50AAAAAAALAAAAAQAAA+kAAAACAAAAAw==',
        'AAAAAAAAADZBZG1pbi1vbmx5OiB3aGl0ZWxpc3QgYSB0b2tlbiBzbyB1c2VycyBjYW4gZGVwb3NpdCBpdC4AAAAAABNhZGRfc3VwcG9ydGVkX3Rva2VuAAAAAAEAAAAAAAAABXRva2VuAAAAAAAAEwAAAAEAAAPpAAAAAgAAAAM=',
      ]),
      options,
    );
  }
}
